name: CI
on: [
  push,
  pull_request
]
jobs:
  build-then-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'         
      - name: Build
        run: |
          go version
          make
      - name: Unit Tests
        run: go test -v ./...
